include:
  - local: 'ci/variables.yml'
  - local: 'ci/rules.yml'
  - local: 'ci/templates.yml'
  - local: 'ci/stages.yml'
  - local: 'ci/test.yml'
  - local: 'ci/merge.yml'
  - local: 'ci/docker.yml'
  - local: 'ci/backup.yml'
  - local: 'ci/deploy.yml'
  - local: 'ci/cleanup.yml'