FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Add user
RUN addgroup -S transitlinkgroup && adduser -S transitlink -G transitlinkgroup
USER transitlink

# Expose application port
EXPOSE 8888

# Healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
