server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://${TRANSITLINK_DB_HOST}:${TRANSITLINK_DB_PORT}/${TRANSITLINK_DB_NAME}
    username: ${TRANSITLINK_DB_USER}
    password: ${TRANSITLINK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  hikari:
    pool-name: HikariPool-TransitDB
    connection-timeout: 30000
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true
    connection-init-sql: SELECT version()

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
