server:
  port: ${TRANSITLINK_PORT:8888}

spring:
  jackson:
    time-zone: UTC

  datasource:
    url: jdbc:postgresql://${TRANSITLINK_DB_HOST}:${TRANSITLINK_DB_PORT}/${TRANSITLINK_DB_NAME}
    username: ${TRANSITLINK_DB_USER}
    password: ${TRANSITLINK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-TransitLink
      connection-init-sql: "SET time zone 'UTC';"
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 3000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    enabled: true
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    from: ${SMTP_FROM_EMAIL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectionpoolsize: 10
      mail.smtp.connectiontimeout: 5000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  servlet:
    multipart:
      max-file-size: ${TRANSITLINK_MAX_FILE_SIZE:"50MB"}
      max-request-size: ${TRANSITLINK_MAX_REQUEST_SIZE:"50MB"}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  file:
    name: ${TRANSITLINK_WORKING_DIR:"."}/logs/transitlink.log
  logback:
    rollingpolicy:
      max-file-size: ${TRANSITLINK_MAX_LOG_FILE_SIZE:10MB}
      max-history: ${TRANSITLINK_MAX_LOG_HISTORY:7}
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG


app:
  storage:
    provider: ${TRANSITLINK_STORAGE_PROVIDER:"local"}
    root-path: ${TRANSITLINK_WORKING_DIR:"."}/data
    base-url: ${TRANSITLINK_SCHEMA}://${TRANSITLINK_DOMAIN}/files
  security:
    permit-all:
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /files/**
      - /actuator/health
      - /actuator/info
      - /login/oauth2/**
      - /api/identity/auth/**
      - /oauth2/**
    cors:
      allowed-origins:
        - "http://localhost:4200"
        - "http://localhost:8888"
        - "http://api.transitlink.fpt.edu.vn"
        - "https://api.transitlink.fpt.edu.vn"
        - "https://api.transitlink.dpdns.org"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
    jwt:
      secret: ${JWT_SECRET}
      access-token:
        expiration: 900000 # 15 phút (ms)
      refresh-token:
        expiration: 604800000 # 7 ngày (ms)
    oauth2:
      redirect-uris:
        - http://localhost:4200/oauth/callback
    verification:
      otp-expiration-minutes: 5
      max-attempts: 5
      rate-limit-minutes: 1
    frontend:
      base-url: "http://localhost:4200"


# SpringDoc configuration for API documentation
springdoc:
  api-docs:
    enabled: true # change false to disable API docs on production

  swagger-ui:
    enabled: true # change false to disable Swagger UI on production

  info:
    title: TransitLink API
    version: 1.0.0
    description: API documentation for the TransitLink application

  servers:
    - url: http://localhost:8888
      description: Local development server
    - url: http://api.transitlink.fpt.edu.vn
      description: Containerized depvloyment server

  groups:
    - group: auth
      paths: /api/identity/**
    - group: storage
      paths: /api/storage/**