server:
  port: 0

spring:
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      max-lifetime: 20000
      idle-timeout: 10000
      minimum-idle: 0
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true

  data:
    redis:
      enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: false
    info:
      enabled: false

logging:
  level:
    root: WARN
